import type { AShareStock } from "../types.js";

export const FALLBACK_A_SHARE_FIXTURE: AShareStock[] = [
  {
    code: "300308",
    name: "中际旭创",
    latestPrice: null,
    pctChange: null,
    totalMarketCap: 130_000_000_000,
    floatMarketCap: null,
    pe: 42,
    turnover: 3.2,
    mainNetInflow: 10_000_000,
    industry: "通信设备",
    region: "山东板块",
    concept: "CPO 光模块 硅光 AI算力",
  },
  {
    code: "300502",
    name: "新易盛",
    latestPrice: null,
    pctChange: null,
    totalMarketCap: 110_000_000_000,
    floatMarketCap: null,
    pe: 48,
    turnover: 4.2,
    mainNetInflow: 8_000_000,
    industry: "通信设备",
    region: "四川板块",
    concept: "CPO 光模块 硅光",
  },
  {
    code: "688072",
    name: "拓荆科技",
    latestPrice: null,
    pctChange: null,
    totalMarketCap: 48_000_000_000,
    floatMarketCap: null,
    pe: 75,
    turnover: 4.1,
    mainNetInflow: 8_000_000,
    industry: "半导体设备",
    region: "辽宁板块",
    concept: "半导体 刻蚀 薄膜 先进封装 国产替代",
  },
  {
    code: "688017",
    name: "绿的谐波",
    latestPrice: null,
    pctChange: null,
    totalMarketCap: 20_000_000_000,
    floatMarketCap: null,
    pe: 95,
    turnover: 3.8,
    mainNetInflow: 2_000_000,
    industry: "机器人",
    region: "江苏板块",
    concept: "机器人 减速器 执行器",
  },
  {
    code: "002384",
    name: "东山精密",
    latestPrice: null,
    pctChange: null,
    totalMarketCap: 50_000_000_000,
    floatMarketCap: null,
    pe: 30,
    turnover: 2.2,
    mainNetInflow: 1_000_000,
    industry: "消费电子",
    region: "江苏板块",
    concept: "先进封装 PCB 光模块",
  },
  {
    code: "600000",
    name: "浦发银行",
    latestPrice: null,
    pctChange: null,
    totalMarketCap: 260_000_000_000,
    floatMarketCap: null,
    pe: 6,
    turnover: 0.2,
    mainNetInflow: -1_000_000,
    industry: "银行",
    region: "上海板块",
    concept: "金融",
  },
];
