import type { SourceRecord } from "../types.js";

export const SEED_SOURCES: SourceRecord[] = [
  {
    id: "P0-CNINFO-ANNOUNCEMENTS",
    title: "巨潮资讯 A股公司公告与定期报告",
    tier: "P0",
    sourceType: "primary",
    publisher: "CNINFO / 深圳证券信息有限公司",
    observedAt: "2026-06-01",
    url: "https://www.cninfo.com.cn/",
    summary: "A股上市公司公告、年报、半年报、招股书、监管问询与回复等主来源目录；仅作为主来源入口，候选级结论必须引用具体公司文件。",
    evidenceTags: ["primary-registry", "filings", "annual-report", "announcement", "a-share"],
  },
  {
    id: "P0-SSE-DISCLOSURE",
    title: "上海证券交易所上市公司信息披露",
    tier: "P0",
    sourceType: "primary",
    publisher: "上海证券交易所",
    observedAt: "2026-06-01",
    url: "https://www.sse.com.cn/disclosure/listedinfo/announcement/",
    summary: "沪市上市公司公告、监管信息、定期报告与临时公告主来源目录；候选级结论必须落到具体公告或报告。",
    evidenceTags: ["primary-registry", "sse", "filings", "announcement", "a-share"],
  },
  {
    id: "P0-SZSE-DISCLOSURE",
    title: "深圳证券交易所上市公司公告",
    tier: "P0",
    sourceType: "primary",
    publisher: "深圳证券交易所",
    observedAt: "2026-06-01",
    url: "https://www.szse.cn/disclosure/listed/notice/",
    summary: "深市上市公司公告、监管函、定期报告与临时公告主来源目录；候选级结论必须落到具体公告或报告。",
    evidenceTags: ["primary-registry", "szse", "filings", "announcement", "a-share"],
  },
  {
    id: "P0-SSE-INTERACTIVE-E",
    title: "上证 e 互动投资者问答",
    tier: "P0",
    sourceType: "primary",
    publisher: "上海证券交易所",
    observedAt: "2026-06-01",
    url: "https://sns.sseinfo.com/",
    summary: "沪市公司投资者问答与公司回复主来源入口；只能作为公司表述证据，需与公告、年报或客户/订单证据交叉验证。",
    evidenceTags: ["primary-registry", "investor-relations", "management-commentary", "a-share"],
  },
  {
    id: "P0-SZSE-IRM",
    title: "深交所互动易投资者关系",
    tier: "P0",
    sourceType: "primary",
    publisher: "深圳证券交易所",
    observedAt: "2026-06-01",
    url: "https://irm.cninfo.com.cn/",
    summary: "深市互动易公司回复主来源入口；只能作为公司表述证据，需与公告、年报或客户/订单证据交叉验证。",
    evidenceTags: ["primary-registry", "investor-relations", "management-commentary", "a-share"],
  },
  {
    id: "SERENITY-X-ARTICLE-SIVE-20260519",
    title: "SIVE - The CPO Laser Chokepoint for Hyperscalers",
    tier: "P2",
    sourceType: "social",
    publisher: "Serenity / X Articles",
    observedAt: "2026-05-31",
    url: "https://x.com/aleabitoreddit/status/2056691097594925522",
    summary:
      "Primary long-form Serenity article explaining how to map a hidden CPO laser bottleneck through disclosed customers, high-confidence customer inference, capacity, TAM, and negative execution risks.",
    evidenceTags: ["Serenity", "CPO", "photonics", "customer-mapping", "bottleneck"],
  },
  {
    id: "SERENITY-X-PROFILE-20260531",
    title: "Serenity X profile and Articles list",
    tier: "P2",
    sourceType: "social",
    publisher: "X",
    observedAt: "2026-05-31",
    url: "https://x.com/aleabitoreddit",
    summary:
      "Profile describes Serenity as AI/Semi supply-chain analyst trading unknown bottlenecks; live Chrome read showed 6,917 posts and X Articles including SIVE, robotics, crypto policy, and gold-rush bottleneck articles.",
    evidenceTags: ["Serenity", "profile", "articles"],
  },
  {
    id: "BAILI-SERENITY-BAYES-THREAD-20260531",
    title: "Baili thread summarizing Serenity's investment logic",
    tier: "P2",
    sourceType: "social",
    publisher: "X / Baili1018",
    observedAt: "2026-05-31",
    url: "https://x.com/Baili1018/status/2060903590169133358",
    summary:
      "Chinese thread interprets Serenity's process as Bayesian: high-quality priors from papers/BOM/supply-chain maps, early action under uncertainty, evidence updates during holding, and rotation to the highest posterior bottleneck.",
    evidenceTags: ["Bayesian", "methodology", "supply-chain-map", "rotation"],
  },
  {
    id: "SERENITY-REPLY-DISTILLATION-20260530",
    title: "leslieyeo/serenity-reply methodology distillation",
    tier: "P1",
    sourceType: "repo",
    publisher: "GitHub / leslieyeo",
    observedAt: "2026-06-01",
    url: "https://github.com/leslieyeo/serenity-reply",
    summary:
      "MIT-licensed external distillation of Serenity's public methodology, decision heuristics, limitations, and response boundaries. Used as methodology input only, not as primary company evidence or a runtime persona skill.",
    evidenceTags: ["Serenity", "methodology-distillation", "reasoning-provenance", "non-impersonation", "MIT"],
  },
  {
    id: "SERENITY-REPLY-EVALS-20260530",
    title: "serenity-reply regression and red-team eval set",
    tier: "P1",
    sourceType: "repo",
    publisher: "GitHub / leslieyeo",
    observedAt: "2026-06-01",
    url: "https://github.com/leslieyeo/serenity-reply/blob/main/tests/eval-set.md",
    summary:
      "External regression set covering attribution boundaries, high-risk trading refusal, extrapolation labeling, and anti-persona overreach. Used to inform local harness checks.",
    evidenceTags: ["Serenity", "eval", "red-team", "risk-boundary", "methodology-quality"],
  },
  {
    id: "TOPICDIGG-SERENITY-PROFILE",
    title: "TopicDigg Serenity profile mirror",
    tier: "P2",
    sourceType: "social",
    publisher: "TopicDigg",
    observedAt: "2026-05-31",
    url: "https://topicdigg.com/x/aleabitoreddit",
    summary:
      "Public mirror of recent Serenity posts used only for accessible metadata, short excerpts, and source IDs when X is unstable.",
    evidenceTags: ["Serenity", "mirror", "recent-posts"],
  },
  {
    id: "TWISCAN-SERENITY-PROFILE",
    title: "Twiscan Serenity profile mirror",
    tier: "P2",
    sourceType: "social",
    publisher: "Twiscan",
    observedAt: "2026-05-31",
    url: "https://twiscan.com/en/x/aleabitoreddit",
    summary:
      "Alternative public profile mirror used for cross-checking recent Serenity posts and follower/profile metadata.",
    evidenceTags: ["Serenity", "mirror", "cross-check"],
  },
  {
    id: "PI-AGENT-BASE",
    title: "earendil-works/pi Pi Agent Harness Mono Repo",
    tier: "P1",
    sourceType: "repo",
    publisher: "GitHub / earendil-works",
    observedAt: "2026-05-31",
    url: "https://github.com/earendil-works/pi",
    summary:
      "Pi provides @earendil-works/pi-agent-core, a stateful tool-calling agent runtime used as this project's base harness.",
    evidenceTags: ["pi", "agent-harness", "tool-calling"],
  },
  {
    id: "OPENSPEC-FISSION",
    title: "Fission-AI OpenSpec",
    tier: "P1",
    sourceType: "repo",
    publisher: "GitHub / Fission-AI",
    observedAt: "2026-05-31",
    url: "https://github.com/Fission-AI/OpenSpec",
    summary:
      "OpenSpec is used for the spec-driven proposal, design, requirements, and task artifacts for this implementation.",
    evidenceTags: ["openspec", "spec-driven-development"],
  },
  {
    id: "GITHUB-FINANCE-AGENT-SCAN-20260531",
    title: "GitHub finance agent landscape scan",
    tier: "P1",
    sourceType: "repo",
    publisher: "GitHub/Web search",
    observedAt: "2026-05-31",
    summary:
      "Landscape scan identified OpenBB, TradingAgents-CN, financial-research-analyst-agent, A-share investment agent forks, and Feishu/WeChat daily stock-analysis skills as relevant harness references.",
    evidenceTags: ["github-scan", "financial-agent", "a-share", "rag", "feishu"],
  },
  {
    id: "P1-SINA-300308-RESEARCH-20260531",
    title: "中际旭创研究报告：全球光模块龙头，AI算力驱动业绩高增",
    tier: "P1",
    sourceType: "broker_report",
    publisher: "新浪财经 / 公开研报转载",
    observedAt: "2026-06-01",
    url: "https://finance.sina.com.cn/stock/relnews/cn/2026-05-31/doc-inhzuzxi5808493.shtml",
    summary: "公开研究报告转载，讨论中际旭创作为高速光模块方案提供商，在 AI 算力、CPO、1.6T 硅光等方向的产品和需求线索。",
    evidenceTags: ["300308", "中际旭创", "broker-report", "CPO", "光模块", "硅光", "客户", "产能"],
  },
  {
    id: "P1-DFCF-300502-RESEARCH-20260527",
    title: "山西证券-新易盛：1.6T环比上量将加快，盈利能力继续维持行业领先水平",
    tier: "P1",
    sourceType: "broker_report",
    publisher: "东方财富 Choice / 山西证券",
    observedAt: "2026-06-01",
    url: "https://pdf.dfcfw.com/pdf/H3_AP202605271822907857_1.pdf?1779880599000.pdf=",
    summary: "公开 PDF 研报，围绕新易盛 1.6T 光模块、OCS/XPO/NPO 等新品、Scale-up 需求和物料/产能释放风险进行跟踪。",
    evidenceTags: ["300502", "新易盛", "broker-report", "1.6T", "光模块", "CPO", "NPO", "客户", "产能"],
  },
  {
    id: "P1-SINA-002384-RESEARCH-202605",
    title: "东山精密：2026Q1业绩高增，“光模块+AI PCB”打开成长空间",
    tier: "P1",
    sourceType: "broker_report",
    publisher: "新浪财经 / 公开研报转载",
    observedAt: "2026-06-01",
    url: "https://stock.finance.sina.com.cn/stock/go.php/vReport_Show/kind/search/rptid/830959515923/index.phtml",
    summary: "公开研报页面，跟踪东山精密 2026Q1 业绩、光模块与 AI PCB 增长空间，并以公司年报和一季报作为事件基础。",
    evidenceTags: ["002384", "东山精密", "broker-report", "光模块", "AI PCB", "PCB", "先进封装", "客户", "产能"],
  },
  {
    id: "P1-SINA-688072-RESEARCH-202604",
    title: "拓荆科技：新品性能优异，先进制程领域核心竞争力提升",
    tier: "P1",
    sourceType: "broker_report",
    publisher: "新浪财经 / 公开研报转载",
    observedAt: "2026-06-01",
    url: "https://stock.finance.sina.com.cn/stock/go.php/vReport_Show/kind/lastest/rptid/828125602337/index.phtml",
    summary: "公开研报页面，讨论拓荆科技 SEMICON China 2026 新品、ALD/Gap-fill 等设备、先进制程应用和募投产能释放。",
    evidenceTags: ["688072", "拓荆科技", "broker-report", "先进封装", "半导体", "刻蚀", "薄膜", "客户", "订单", "产能"],
  },
  {
    id: "P1-SINA-688017-RESEARCH-202605",
    title: "绿的谐波：2025年报及2026年一季报点评，产品规模化能力提升",
    tier: "P1",
    sourceType: "broker_report",
    publisher: "新浪财经 / 公开研报转载",
    observedAt: "2026-06-01",
    url: "https://stock.finance.sina.com.cn/stock/go.php/vReport_Show/kind/search/rptid/831433872355/index.phtml",
    summary: "公开研报页面，围绕绿的谐波年报和一季报，跟踪谐波减速器、国际头部机器人客户批量交付、产品出货和规模化能力。",
    evidenceTags: ["688017", "绿的谐波", "broker-report", "机器人", "减速器", "执行器", "客户", "订单", "产能"],
  },
];
